spring:

  # Service name in Eureka
  application:
    name: wallet-service
    
  # Database MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3355/wallet
    username: root
    password: bfhs7Hi38o1Bas8jH90VS

# Discovery Eureka Server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# Tomcat port
server:
  port: 1001